#!/data/data/com.termux/files/usr/bin/sh
tsu -c base /data/data/com.termux/files/home/TWRP-USES/Maruf/Port/.repackimg.sh
tsu -c base /data/data/com.termux/files/home/TWRP-USES/Maruf/Stock/.repackimg.sh
