#!/data/data/com.termux/files/usr/bin/sh
cd /data/data/com.termux/files/home/TWRP-USES/Maruf/Port
tsu -c ./.unpackimg.sh
cd /data/data/com.termux/files/home/TWRP-USES/Maruf/Stock
tsu -c ./.unpackimg.sh
